### PR TITLE
Allow python3 compatability with six module and travisCL

### PR DESCRIPTION
**Pull request by joshblum**
Fully address #30

### CODE REVIEW

**Comment by jgorset** [comment]
Thanks, @joshblum! This is great.

**Comment by igorcamp** [comment]
I tested it in a python 3.4 project and didn't work. I tested it again changing back six.u to decode() and worked.

**Comment by joshblum** [comment]
@igorcamp what broke exactly?

**Comment by igorcamp** [comment]
@joshblum "TypeError: Type str doesn't support the buffer API" in this line:
if stderr and 'no crontab for' not in six.u(stderr):

**Comment by joshblum** [comment]
good find! fixed in #37

**Pull request merged**
