### PR TITLE
Register with args

### PR DESCRIPTION
**Pull request by paulochf**
Tests passing, but it would be nice if you review it.

```
$ sh runtests.sh
Creating test database for alias 'default'...
Installed 3 tasks.
.Installed 3 tasks.
..........
----------------------------------------------------------------------
Ran 11 tests in 0.237s

OK
```

I'm using it about a month, works nicely.

This PR refers to issue jgorset/django-kronos/issues/23

### CODE REVIEW

**Comment by jgorset** [comment]
Thanks, @paulochf! This is a great pull request, but I'm not sure that I understand the use case: In the example provided in the README, why pass the arguments in the decorator instead of just placing them in the task itself?

:cake:

**Comment by paulochf** [comment]
Because you put the decorator on a command writing only the cron time specifications. The path (like `/path/to/python /path/to/manage.py command`) is filled by django-kronos. Given that, how one could put arguments after the paths above just writing the decorator?

If it's obvious, I missed, sorry.

**Comment by paulochf** [comment]
PS: supposing that your command you use the decorator on was implemented to accept command line parameters, parsed by optparse, argparse, etc.

**Comment by jgorset** [comment]
Right! Okay, that makes sense. I was just thrown off by the example – unless I'm really missing something, there's not much point to parsing command-line arguments in a task (they're static anyway, so you might as well just hard code them in the task itself). I can definitely see the use case when you're registering Django commands that already accept command line arguments with Kronos, though.

Please do let me know if I'm totally wrong about this and there's plenty of point to using arguments with tasks, but otherwise I'll leave this open pending a change to the README to describe the use case.

**Comment by paulochf** [comment]
An usage example: https://gist.github.com/paulochf/efc28e5a6449a9df85ac.

It's a Django command, which can get options from command line, and with django-kronos I can schedule some runs with different parameters.

I only could achieve that with this PR.

**Comment by jgorset** [comment]
Perfectly, thanks @paulochf! I'll merge and revise the README to reflect its intended use case (that is registering existing Django commands that accept arguments rather than Kronos tasks).

**Comment by jgorset** [comment]
You get :cake:!

**Pull request merged**
