### PR TITLE
remove tasks from the project that have the breadcrumb

### PR DESCRIPTION
**Pull request by ungrok**
This is for issue #35

### CODE REVIEW

**Comment by jgorset** [comment]
Thanks @ungrok, but doesn't this evaluate to the same? It checked whether the expression was in the lane before, and it still does that now.

**Comment by ungrok** [comment]
If a line just contains one of the values '$KRONOS_BREAD_CRUMB' or exp it would also be removed. The other way to write the check is to switch the `and` for an `or`.

**Comment by ungrok** [comment]
@jgorset I pushed up a test case for the removing of cron jobs. Let me know what else you need to get this pulled in.

**Comment by jgorset** [comment]
Right, it's the double negative that got me – sorry, and sorry for taking so long to merge this!

**Pull request merged**
