### PR TITLE
Test on django 1.9 as well

### PR DESCRIPTION
**Pull request by joshblum**

### CODE REVIEW

**Comment by joshblum** [comment]
@jgorset is this package still maintained? Tests are failing on master :/

**Comment by jgorset** [comment]
It is! Sorta! It's maintained by the people who need it, like yourself. I'm not sure how the tests started failing, though, but I can check it out as time permits. I'm also happy to accept pull requests. 😃

**Comment by joshblum** [comment]
Cool, I'll take a look!

**Comment by joshblum** [comment]
@jgorset passing now, let me know what you think!

**Comment by jgorset** [comment]
You're awesome, @joshblum! :sparkles: :cake: :sparkles:

**Pull request merged**
