### PR TITLE
Added support for registering django commands

### PR DESCRIPTION
**Pull request by carrerasrodrigo**
- Support for django commands
- Code refactoring
- Removed unused imports
- Docs updated
- Added new tests cases
- New version
- Added contributors file
- Added support for python 3.4

### CODE REVIEW

**Comment by jgorset** [comment]
Hi @carrerasrodrigo, and thanks so much! It's great to support django commands in kronos.

**Comment by jgorset** [comment]
I think this warrants a new version 0.6, but in the future please don't bump the version of a library in a pull request (or at least do it in a separate commit so that the maintainer can cherry pick it).

**Comment by jgorset** [comment]
This should now be available on the cheese factory as v0.6. Thanks again!

**Comment by carrerasrodrigo** [comment]
Thank you very much @jgorset !

**Pull request merged**
